P8105 Homework 2 Solutions
================
Meghan Bellerose,
September 24, 2020

This homework uses r version 4.0.2 and r studio version 1.3.1073.

For this homework, I need the tidyverse and readxl libraries.

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

### Read and clean Mr. Trash Wheel data

First, I will read the Mr. Trash Wheel Excel data sheet, create snake
format variable names, and omit non-data entries, including rows and
columns with notes and figures, as well as entries that are unrelated to
the dumpster data.

I’ll also round the number of sports balls to the nearest integer and
convert the results to an integer variable.

``` r
trashwheel_df =
  read_xlsx("./data/trash_wheel.xlsx",
  sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N")) %>%
  janitor:: clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  ) 
```

### Read and clean precipitation data

Next, I’ll read and clean the precipitation data for 2017 and 2018,
omitting rows without data and adding a variable for year.

``` r
precip_2018 = 
  read_excel("./data/trash_wheel.xlsx",
      sheet = "2018 Precipitation",
      skip = 1
  ) %>%
  janitor:: clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 = 
  read_excel("./data/trash_wheel.xlsx",
      sheet = "2017 Precipitation",
      skip = 1
  ) %>%
  janitor:: clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```

Now I will combine the precipitation datasets and convert month to a
character variable using month.name.

``` r
precip_df = 
  bind_rows(precip_2017, precip_2018) %>%
  mutate(month = month.name[month])
```

The square bracket vector is not ideal, so we can create a month data
frame instead.

``` r
options(tibble.print_min = 3)

month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df = 
  bind_rows(precip_2017, precip_2018)

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##    year month total month_name
    ##   <dbl> <dbl> <dbl> <chr>     
    ## 1  2017     1  2.34 January   
    ## 2  2017     2  1.46 February  
    ## 3  2017     3  3.57 March     
    ## # … with 21 more rows

This dataset contains information from the Mr. Trashwheel collector in
Baltimore, MD. As trash enters the inner harbor, the trashwheel collects
the trasha and stores it in a dumpster. The dataset contains information
on year, month, weight of the trash collected, and the number of some
specific types of trash, such as plastic bottles or sports balls. For
instance, in 2017, the median number of sports balls inside a dumpster
after collection was 8 balls. There are 344 rows in our final dataset.

Additional data sheets include monthly precipitation data. In 2017, the
mean precipitation was 2.7 inches, and in 2018 it was 5.9 inches.

This code can be used with the 2020 data, because the sheet names are
consistent\!

# Problem 2

### Read and clean the NYC Transit dataset

I will read and clean the NYC transit dataset, keeping important
variables.

``` r
options(tibble.print_min = 3)

subway_df =
  read_csv("./data/subway.csv", 
    col_types = "cccnnccccccccccccccccclclcccnncc") %>%
  janitor:: clean_names() %>%
  select(
      line, station_name, station_location, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, vending, entry, entrance_type, ada)

subway_tidy_data = 
  pivot_longer(
    subway_df,
    route1:route11,
    names_to = "route_order",
    names_prefix = "route",
    values_to = "route") %>%
  drop_na(route)

subway_tidy_data
```

    ## # A tibble: 4,270 x 9
    ##   line  station_name station_location vending entry entrance_type ada  
    ##   <chr> <chr>        <chr>            <chr>   <chr> <chr>         <lgl>
    ## 1 4 Av… 25th St      (40.660397, -73… YES     YES   Stair         FALSE
    ## 2 4 Av… 25th St      (40.660397, -73… YES     YES   Stair         FALSE
    ## 3 4 Av… 36th St      (40.655144, -74… YES     YES   Stair         FALSE
    ## # … with 4,267 more rows, and 2 more variables: route_order <chr>, route <chr>

I then converted the entry variable from a character to a logical
variable.

``` r
as.logical(pull(subway_tidy_data, entry))
```

This dataset contains information about the NYC transit systems’ subway
stations. I cleaned the dataset so that variable names are in snake
format and only retained information on the station names and locations,
the routes that are served by each station during weekday service,
whether the location allows entry, the entrance type, whether vending
machines are available, and whether it is ADA accessible. I tidied the
data so that routes 1 through 11 were listed in a single column rather
than 11 columns and rows with NA are removed. I then converted entry
from a character to a logical vector. There are 1868 rows and 18 columns
in the final dataset. I consider the data to be tidy.

### NYC Transit system details

Next, I will find the number of distinct stations, the number of ADA
compliant stations, and the proportion of stations without vending
machines that allow entrance.

``` r
distinct(subway_tidy_data, station_name)
```

    ## # A tibble: 356 x 1
    ##   station_name
    ##   <chr>       
    ## 1 25th St     
    ## 2 36th St     
    ## 3 45th St     
    ## # … with 353 more rows

``` r
filter (subway_tidy_data, ada == TRUE) %>%
  distinct(station_name)
```

    ## # A tibble: 73 x 1
    ##   station_name            
    ##   <chr>                   
    ## 1 Atlantic Av-Barclays Ctr
    ## 2 DeKalb Av               
    ## 3 Pacific St              
    ## # … with 70 more rows

``` r
filter (subway_tidy_data, vending == "NO") %>%
  filter (entry == "YES")
```

    ## # A tibble: 139 x 9
    ##   line  station_name station_location vending entry entrance_type ada  
    ##   <chr> <chr>        <chr>            <chr>   <chr> <chr>         <lgl>
    ## 1 4 Av… 9th St       (40.670847, -73… NO      YES   Stair         FALSE
    ## 2 4 Av… 9th St       (40.670847, -73… NO      YES   Stair         FALSE
    ## 3 4 Av… 9th St       (40.670847, -73… NO      YES   Stair         FALSE
    ## # … with 136 more rows, and 2 more variables: route_order <chr>, route <chr>

``` r
filter (subway_tidy_data, vending == "NO")
```

    ## # A tibble: 447 x 9
    ##   line  station_name station_location vending entry entrance_type ada  
    ##   <chr> <chr>        <chr>            <chr>   <chr> <chr>         <lgl>
    ## 1 4 Av… 53rd St      (40.645069, -74… NO      NO    Stair         FALSE
    ## 2 4 Av… 77th St      (40.629742, -74… NO      NO    Stair         FALSE
    ## 3 4 Av… 9th St       (40.670847, -73… NO      YES   Stair         FALSE
    ## # … with 444 more rows, and 2 more variables: route_order <chr>, route <chr>

``` r
139/447
```

    ## [1] 0.310962

There are 356 distinct stations, and 73 are ADA compliant. Among the 447
stations without vending machines, 139 (0.31%) allow entry.

I already made the route number and name distinct variables during my
data tidying process. I determine how many stations serve the A train,
and among those, how many are ADA compliant below.

``` r
filter (subway_tidy_data, route == "A")
```

    ## # A tibble: 273 x 9
    ##   line  station_name station_location vending entry entrance_type ada  
    ##   <chr> <chr>        <chr>            <chr>   <chr> <chr>         <lgl>
    ## 1 42nd… Times Square (40.755983, -73… YES     YES   Stair         FALSE
    ## 2 8 Av… 125th St     (40.811109, -73… YES     YES   Stair         FALSE
    ## 3 8 Av… 125th St     (40.811109, -73… YES     YES   Stair         FALSE
    ## # … with 270 more rows, and 2 more variables: route_order <chr>, route <chr>

``` r
filter (subway_tidy_data, route == "A") %>% 
  filter(ada == TRUE)
```

    ## # A tibble: 107 x 9
    ##   line  station_name station_location vending entry entrance_type ada  
    ##   <chr> <chr>        <chr>            <chr>   <chr> <chr>         <lgl>
    ## 1 8 Av… 14th St      (40.740893, -74… YES     YES   Easement      TRUE 
    ## 2 8 Av… 14th St      (40.740893, -74… YES     YES   Stair         TRUE 
    ## 3 8 Av… 14th St      (40.740893, -74… YES     YES   Stair         TRUE 
    ## # … with 104 more rows, and 2 more variables: route_order <chr>, route <chr>

There are 273 distinct stations that serve the A train. Of these, 107
are ADA compliant.

# Problem 3

### Read and clean FiveThirtyEight data

First I read and clean the data in the pols-month csv file. I break the
date variable into day, month, and year then remove day. I will then
create a variable for president and remove the base variables used to
create it.

``` r
options(tibble.print_min = 3)

pols_df =
  read_csv("./data/pols-month.csv") %>% 
  separate(mon, c("year", "month", "day")) %>% 
  mutate(
    prez_dem = replace(prez_dem, prez_dem == 1, "dem"),
    prez_dem = replace(prez_dem, prez_dem == 0, "gop"),
    president = prez_dem
  ) %>%
  mutate(
    month = replace(month, month == "01", "1"),
    month = replace(month, month == "02", "2"),
    month = replace(month, month == "03", "3"),
    month = replace(month, month == "04", "4"),
    month = replace(month, month == "05", "5"),
    month = replace(month, month == "06", "6"),
    month = replace(month, month == "07", "7"),
    month = replace(month, month == "08", "8"),
    month = replace(month, month == "09", "9")
  ) %>% 
  select(year, month, president, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem)
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

I’ll repeat this process for the snp csv file and arrange the data file
so that year and month are first.

``` r
snp_df =
  read_csv("./data/snp.csv") %>% 
  separate(date, c("month", "day", "year")) %>% 
  select (year, month, close)
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

Now I tidy the unemployment data to prepare it for merging. I also
change it from wide to long format.

``` r
unemployment_df =
  read_csv("./data/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month_name",
    values_to = "percent_unemployed"
  ) %>% 
  rename(
    year = Year
  )
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.abb
  )

unemployment_month_data = 
  left_join(unemployment_df, month_df, by = "month_name") %>% 
  select(year, month, percent_unemployed)
```

Now I join the three datasets.

``` r
combined_data = 
  left_join(pols_df, snp_df, unemployment_month_data, by = c("year", "month"))

combined_data
```

    ## # A tibble: 822 x 10
    ##   year  month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ##   <chr> <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <dbl>
    ## 1 1947  1     dem            23      51     253      23      45     198    NA
    ## 2 1947  2     dem            23      51     253      23      45     198    NA
    ## 3 1947  3     dem            23      51     253      23      45     198    NA
    ## # … with 819 more rows
